### PR TITLE
Use `none?` so comparison between where/not can be shared

### PR DESCRIPTION
**Pull request by kaspth**
@joeldrapper hey! I'm really curious about this gem. I think we could share the compare logic here if we use Enumerable's `none?` method. What do you think?

### CODE REVIEW

**Comment by kaspth** [comment]
I actually don't know how this works, since `@result = true` is set in `initialize`, I don't see how we're reaching the `@result = false if …` checks?

I mean, I'd have thought Predicate would do something like this?

```ruby
def initialize(record)
  @record = record
  @result = false
end

def where(**kwargs)
  @result ||= kwargs.none? { … } # Same structure for the other methods but the check varies.
  self
end
```

**Comment by joeldrapper** [comment]
Hey @kaspth, thank you so much for opening this! ❤️ I really like the idea of extracting the `compare` method. I don’t know why but you need to use `any?` with `!compare` as it’s different to `none?` with `compare`. 🤯

The reason we set `@result` to `true` in the initializer is for performance so we can skip any additional checks the moment one check comes back negative. We could do it the other way to take advantage of the nice `@result ||=` pattern but then we’d have to invert the result at the end.

**Comment by kaspth** [comment]
@joeldrapper there we go, this should work now.

I get it now, last week my brain couldn't process `return self unless @result` and it looked to me as if we were always returning immediately.

**Comment by joeldrapper** [comment]
Thank you for this! It’s really cool to hear that you were interested in the gem.

**Pull request merged**
